# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Ícaro's Vault
tagline:          'A Jekyll theme'
description:      'I am a Android and Web Developer driven by challenge eager to leave his mark in this world. Crazy for code well indented!'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/icaroabreu
